import time
import os
from datetime import date

today = date.today()

def clearScreen():
    os.system('cls' if os.name == 'nt' else 'clear')

def settings():
    print(">- Settings page has not been completed! Come back later.")

def credits():
    print("Esc.")
    time.sleep(1)
    print("Managed By King.Farooq")
    time.sleep(3)
    print("Develpoers: King.Farooq | B3rry")
    time.sleep(3)
    print("Graphic Designers: King.Farooq | Ghxsttttt")
    time.sleep(3)
    print("Advertisment: King.Farooq | ZaxyMb | B3rry | Ghxttttt")
    time.sleep(3)
    print("Instagram - insta goes here")
    time.sleep(3)
    print("Tiktok - tiktok goes here")
    time.sleep(3)
    print("X (Formally known as Twitter) - X (Formally known as Twitter) goes here")
    time.sleep(3)
    print("Youtube - Youtube goes here")
    time.sleep(3)
    print("Website - website goes here")
    time.sleep(3)
    print(" ")
    print("Redirecting in 15 seconds.")
    time.sleep(5)
    print("Redirecting in 10 seconds.")
    time.sleep(5)
    print("Redirecting in 5 seconds.")
    time.sleep(5)
    mainMenu()

            
def computerBoot():
    computerPassword = int(input(">- Enter Security Passcode: "))
    if computerPassword == int(731522):
        print(">- Initializing system.")
        time.sleep(1)
        print(">- Initializing system..")
        time.sleep(1)
        print(">- Initializing system...")
        time.sleep(1)
        print(">- Initializing system... Done!")
        time.sleep(1)
        print(">- Loading resources.")
        time.sleep(1)
        print(">- Loading resources..")
        time.sleep(1)
        print(">- Loading resources...")
        time.sleep(1)
        print(">- Loading resources... Done!")
        time.sleep(1)
        print(">- Applying security protocols.")
        time.sleep(1)
        print(">- Applying security protocols..")
        time.sleep(1)
        print(">- Applying security protocols...")
        time.sleep(1)
        print(">- Applying security protocols... Done!")
        time.sleep(1)
        print(">- Optimizing system.")
        time.sleep(1)
        print(">- Optimizing system..")
        time.sleep(1)
        print(">- Optimizing system...")
        time.sleep(1)
        print(">- Optimizing system... Done!")
        time.sleep(1)
        print(">- Gathering data.")
        time.sleep(1)
        print(">- Gathering data..")
        time.sleep(1)
        print(">- Gathering data...")
        time.sleep(1)
        print(">- Gathering data... Done!")
        time.sleep(1)
        print(">- Finalizing setup.")
        time.sleep(1)
        print(">- Finalizing setup..")
        time.sleep(1)
        print(">- Finalizing setup...")
        time.sleep(1)
        print(">- Finalizing setup... Done!")
        time.sleep(3)
        print("Welcome, Fedrick Lance!")
        time.sleep(5)
    else:
        print("Security Passcode is Invalid/Expired!")
        time.sleep(3)
        computerBoot()

def file():
    clearScreen()
    print("Files Applacation is loading.")
    time.sleep(1)
    print("Files Applacation is loading..")
    time.sleep(1)
    print("Files Applacation is loading...")
    time.sleep(5)
    print("Files Applacation is taking too long to load.")
    time.sleep(1)
    print("Files Applacation is taking too long to load..")
    time.sleep(1)
    print("Accessing Cloud.")
    time.sleep(1)
    print("Accessing Cloud..")
    time.sleep(1)
    print("Accessing Cloud...")
    time.sleep(1)
    print("Accessing Cloud... Done!")
    time.sleep(4)
    clearScreen()
    print("QMirage_v1.0.exe")
    time.sleep(1)
    print("T_Whisper.docx")
    time.sleep(1)
    print("CRift_Bluprints.pdf")
    time.sleep(1)
    print("NSerpent_Encyr.zip")
    time.sleep(1)
    print(" ")
    def fileChoose():
        fileType = input("Enter File to Access: ")
        if fileType == "QMirage_v1.0.exe":
            input("Enter Secured Passcode: ")
            time.sleep(1)
            print("Invalid Passcode.")
            time.sleep(1)
            print("Temperarly Locked.")
        elif fileType == "T_Whisper.docx":
            input("Enter Secured Passcode: ")
            time.sleep(1)
            print("Invalid Passcode.")
            time.sleep(1)
            print("Temperarly Locked.")
        elif fileType == "CRift_Blueprint.pdf":
            input("Enter Secured Passcode: ")
            time.sleep(1)
            print("Invalid Passcode.")
            time.sleep(1)
            print("Temperarly Locked.")
        elif fileType == "NSerpent_Encyr.zip":
            input("Enter Secured Passcode: ")
            time.sleep(1)
            print("Invalid Passcode.")
            time.sleep(1)
            print("Temperarly Locked.")
        else:
            print("File Not Found!")
            time.sleep(2)
            fileChoose()
    fileChoose()

def drawer():
    print("You open the squeaky drawer.")
    time.sleep(1)
    print("You find a screwdriver, along with a few notes.")
    time.sleep(1)
    print("They watch from the shadows.")
    time.sleep(1)
    print("The thrid step is cursed.")
    time.sleep(1)
    print("Whatever happenes, the clock can't strike thirteen.")
    time.sleep(1)
    clearScreen()
    print("You look over at the computer.")
    time.sleep(1)

def displayLevels():
        print(">- Level 0: [Unlocked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        print(">- Level -: [Locked]")
        time.sleep(1)
        # print(">- ----- ----: [Locked]") - after 10 levels completed then print "secret level unlocked" then show the level
        # time.sleep(1)

        levelSelection = int(input(">- Enter Level: "))

        if levelSelection == int(0):
            def levelZero():
                clearScreen()
                print("The current date is: " + (today.strftime("%B %d, %Y")))
                time.sleep(1)
                print("You are in a small dark room,")
                time.sleep(1)
                print("and are sitting on a chair with your hands tied behind your back.")
                time.sleep(1)
                print("A laptop sits on the desk behind you.")
                time.sleep(1)
                print("You notice something shiny and realize,")
                time.sleep(1)
                print("a broken mirror is on the ground in front of you.")
                print(" ")
                input(">- Press [Enter] to continue: ")
                clearScreen()
                print("You have two options.")
                print(" ")
                time.sleep(1)
                print("1. Fall forward and grab the broken glass shard")
                time.sleep(1)
                print(" ")
                time.sleep(1)
                print("2. Look around the room for something else")
                time.sleep(1)
                print(" ")
                singleChoiceOne = int(input("Choose... "))
                print(" ")
                time.sleep(1)
                if singleChoiceOne == int(1):
                    clearScreen()
                    print("You fall forward and grab a glass shard by pushing yourself forward with your feet.")
                    time.sleep(1)
                    print("Using the shard, you cut yourself free.")
                    time.sleep(1)
                    print("After getting up, you walk towards the laptop.")
                    time.sleep(1)
                    print("You feel a light breeze on your right ankle.")
                    print(" ")
                    input(">- Press [Enter] to continue: ")
                    clearScreen()
                    print("You have two options.")
                    print(" ")
                    time.sleep(1)
                    print("1. Continue walking to the laptop")
                    time.sleep(1)
                    print(" ")
                    time.sleep(1)
                    print("2. Check out where the breeze is coming from")
                    time.sleep(1)
                    print(" ")
                    singleChoiceTwo = int(input("Choose... "))
                    print(" ")
                    time.sleep(1)
                    if singleChoiceTwo == int(1):
                        clearScreen()
                        print("You continue walking to the laptop.")
                        time.sleep(1)
                        print("Once you get to the desk with the laptop, you notice half opened drawers on the desk.")
                        time.sleep(1)
                        print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                        input(">- Press [Enter] to continue: ")
                        clearScreen()
                        print("You have two options.")
                        time.sleep(1)
                        print(" ")
                        print("1. Unlock the computer")
                        time.sleep(1)
                        print(" ")
                        print("2. Open the drawer")
                        print(" ")
                        singleChoiceThree = int(input("Choose... "))
                        if singleChoiceThree == int(1):
                            clearScreen()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()
                            clearScreen()
                            print("You have two options.")
                            time.sleep(1)
                            print(" ")
                            print("1. Go through files")
                            time.sleep(1)
                            print(" ")
                            print("2. Go through pictures")
                            print(" ")
                            singleChoiceFour = int(input("Choose... "))
                            if singleChoiceFour == int(1):
                                file()
                            elif singleChoiceFour == int(2):
                                print("0 Pictures Located.")
                                time.sleep(1)
                                print("You look over at the drawers.")
                                drawer()
                        elif singleChoiceThree == int(2):
                            clearScreen()
                            drawer()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()
                    elif singleChoiceTwo == int(2):
                        clearScreen()
                        print("You look around the room.")
                        time.sleep(1)
                        print("You see a vent.")
                        time.sleep(1)
                        print("You try to open the vent but it is screwed shut.")
                        time.sleep(1)
                        print("You try to use a glass shard, but the shard breaks in your hand and cuts deep in your palm.")
                        time.sleep(1)
                        print("You walk towards the computer out of frustration.")
                        time.sleep(3)
                        clearScreen()
                        print("There is a sticky note stuck on the right corner of the computer with the passcode [731522].")
                        time.sleep(1)
                        computerBoot()
                        clearScreen()
                        print("You have two options.")
                        time.sleep(1)
                        print(" ")
                        print("1. Go through files")
                        time.sleep(1)
                        print(" ")
                        print("2. Go through pictures")
                        print(" ")
                        singleChoiceFour = int(input("Choose... "))
                        if singleChoiceFour == int(1):
                            file()
                        elif singleChoiceFour == int(2):
                            print("0 Pictures Located.")
                            time.sleep(1)
                            print("You look over at the drawers.")
                            drawer()
                        if singleChoiceThree == int(1):
                            clearScreen()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()
                            clearScreen()
                            print("You have two options.")
                            time.sleep(1)
                            print(" ")
                            print("1. Go through files")
                            time.sleep(1)
                            print(" ")
                            print("2. Go through pictures")
                            print(" ")
                            singleChoiceFour = int(input("Choose... "))
                            if singleChoiceFour == int(1):
                                file()
                                time.sleep(2)
                                clearScreen()
                                print("You close the computer out of furstration.")
                                drawer()
                            elif singleChoiceFour == int(2):
                                print("0 Pictures Located.")
                                time.sleep(1)
                                print("You look over at the drawers.")
                                drawer()
                        elif singleChoiceThree == int(2):
                            clearScreen()
                            drawer()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()

                elif singleChoiceOne == int(2):
                    clearScreen()
                    print("In the left corner of the room, you see a small vent.")
                    time.sleep(1)
                    print("You try to get up and walk to the vent butyou cant because you are still tied.")
                    time.sleep(1)
                    print("You fall forward and grab a glass shard by pushing yourself forward with your feet.")
                    time.sleep(1)
                    print("Using the shard, you cut yourself free.")
                    time.sleep(1)
                    print("After getting up, you walk towards the laptop.")
                    time.sleep(1)
                    print("You feel a light breeze on your right ankle.")
                    print(" ")
                    input(">- Press [Enter] to continue: ")
                    clearScreen()
                    print("You have two options.")
                    print(" ")
                    time.sleep(1)
                    print("1. Continue walking to the laptop")
                    time.sleep(1)
                    print(" ")
                    time.sleep(1)
                    print("2. Check out where the breeze is coming from")
                    time.sleep(1)
                    print(" ")
                    singleChoiceTwo = int(input("Choose... "))
                    print(" ")
                    time.sleep(1)
                    if singleChoiceTwo == int(1):
                        clearScreen()
                        print("You continue walking to the laptop.")
                        time.sleep(1)
                        print("Once you get to the desk with the laptop, you notice half opened drawers on the desk.")
                        time.sleep(1)
                        print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                        input(">- Press [Enter] to continue: ")
                        clearScreen()
                        print("You have two options.")
                        time.sleep(1)
                        print(" ")
                        print("1. Unlock the computer")
                        time.sleep(1)
                        print(" ")
                        print("2. Open the drawer")
                        print(" ")
                        singleChoiceThree = int(input("Choose... "))
                    elif singleChoiceTwo == int(2):
                        clearScreen()
                        print("You look around the room.")
                        time.sleep(1)
                        print("You see a vent.")
                        time.sleep(1)
                        print("You try to open the vent but it is screwed shut.")
                        time.sleep(1)
                        print("You try to use a glass shard, but the shard breaks in your hand and cuts deep in your palm.")
                        time.sleep(1)
                        print("You walk towards the computer out of frustration.")
                        clearScreen()
                        print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                        time.sleep(1)
                        computerBoot()
                        clearScreen()
                        print("You have two options.")
                        time.sleep(1)
                        print(" ")
                        print("1. Go through files")
                        time.sleep(1)
                        print(" ")
                        print("2. Go through pictures")
                        print(" ")
                        singleChoiceFour = int(input("Choose... "))
                        if singleChoiceFour == int(1):
                            file()
                        elif singleChoiceFour == int(2):
                            print("0 Pictures Located.")
                            time.sleep(1)
                            print("You look over at the drawers.")
                            drawer()
                        if singleChoiceThree == int(1):
                            clearScreen()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()
                            clearScreen()
                            print("You have two options.")
                            time.sleep(1)
                            print(" ")
                            print("1. Go through files")
                            time.sleep(1)
                            print(" ")
                            print("2. Go through pictures")
                            print(" ")
                            singleChoiceFour = int(input("Choose... "))
                            if singleChoiceFour == int(1):
                                file()
                            elif singleChoiceFour == int(2):
                                print("0 Pictures Located.")
                                time.sleep(1)
                                print("You look over at the drawers.")
                                drawer()
                        elif singleChoiceThree == int(2):
                            clearScreen()
                            drawer()
                            print("There is a sticky note stuck on the right corner of the computer with the passcode [731522]")
                            time.sleep(1)
                            computerBoot()

            levelZero()
        else:
            print(">- Complete Previous Levels to Move on.")
            displayLevels()

def singleplayer():
    print(">- Loading Singleplayer.")
    time.sleep(1)
    print(">- Loading Singleplayer..")
    time.sleep(1)
    print(">- Loading Singleplayer...")
    time.sleep(1)
    clearScreen()
    print(">- Welcome to Esc.")
    player = input(">- Enter your Username: ")
    time.sleep(1)
    print(">- Welcome to Esc. " + player + ".")
    input(">- Press [Enter] to continue: ")
    clearScreen()

def mainMenu():
    print(">- Esc.")
    time.sleep(1)
    print(">- Every Choice Has A Consequence...")
    time.sleep(1)
    print("------------------------------------")
    time.sleep(1)
    clearScreen()
    print("Main Menu")
    time.sleep(1)
    print("1. Singleplayer")
    time.sleep(1)
    print("2. Multiplayer")
    time.sleep(1)
    print("3. Settings")
    time.sleep(1)
    print("4. Credits")
    time.sleep(1)
    print("5. Exit")
    time.sleep(1)

    menuChoice = int(input(">- Enter choice: "))
    time.sleep(1)

    if menuChoice == int(1):
        singleplayer()
        displayLevels()
    elif menuChoice == int(2):
        print("Loading Multiplayer.")
        time.sleep(1)
        print("Loading Multiplayer..")
        time.sleep(1)
        print("Loading Multiplayer...")
        time.sleep(1)
        clearScreen()
        # Multiplayer function
        print(">- Welcome to Esc.")
    elif menuChoice == int(3):
        print("Loading Settings.")
        time.sleep(1)
        print("Loading Settings..")
        time.sleep(1)
        print("Loading Settings...")
        time.sleep(1)
        clearScreen()
        settings()
    elif menuChoice == int(4):
        print("Loading Credits.")
        time.sleep(1)
        print("Loading Credits..")
        time.sleep(1)
        print("Loading Credits...")
        time.sleep(1)
        clearScreen()
        credits()
        time.sleep(20)
        clearScreen()
        mainMenu()
        print(">- Welcome to Esc.")
    elif menuChoice == int(5):
        print("Exiting Game.")
        time.sleep(1)
        print("Exiting Game..")
        time.sleep(1)
        print("Exiting Game...")
        time.sleep(1)
        exit()
    else:
        print(">- Invalid Choice! Please try again.")
        time.sleep(1)
        clearScreen()
        mainMenu()

mainMenu()